### ISSUE TITLE
Issue cross computer

### ISSUE THREAD

**Issue by cjallen1** [10up/SketchPress#17]
Upon opening the sketch file (Sketch_Gutenberg_Beta.sketch) a few of the text layers were slightly too short and result in spanning the text over 2 lines, I've reworked the width of some layers and saved in the 10up google drive (10up internal > UX > Shared Sketch Templates) as a duplicated file 'BetaCA'. This file need adding to github, but was unsure how to.

**Comment by jarahsames** [comment]
Merged this - thanks!
