### ISSUE TITLE
Nested Content Blocks

### ISSUE THREAD

**Issue by cjallen1** [10up/SketchPress#19]
Last week, the use of nested content blocks was released, this will need adding into the Sketch template too.

https://make.wordpress.org/core/2018/02/16/whats-new-in-gutenberg-16th-february/

**Comment by jarahsames** [comment]
Thanks, @cjallen1 ! Added to feature list. If you get to any of them first send a pull request and I can merge it to maser.

**Comment by jarahsames** [comment]
@cjallen1 I am going to roll up changes for this in my next iteration of Gutenberg; several other things have changed so I am going to wrap it into one update. Thanks for noting the issue!
