### ISSUE TITLE
Notification Banners

### ISSUE THREAD

**Issue by tddewey** [10up/SketchPress#20]
General notice banners and warning banners. Optional dismissal through a close button.

I don't think WordPress has an error banner (preferring more graceful error handling), but we might include it anyway.

**Comment by jarahsames** [comment]
Thanks - will add this to the feature request list and follow-up with you when it's complete. If you get to it anytime soon feel free to send a pull request and I can merge it to master.

**Comment by jarahsames** [comment]
@tddewey notification, notices, and error banners are included in this most recent version. Thanks again for calling it to my attention!
